### ISSUE TITLE
Class 'CreateFoodNutrientTable' not found

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#11]
Bug Lucy was having today in class. Full error:

PHP Fatal error:  Class 'CreateFoodNutrientTable' not found in /home/vagrant/Code/EECS-393-Nutrition-App/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 324

**Comment by 12wrigja** [comment]
Should have been fixed in commit 5b52b4d73edf015614dc78bff3d675156373de49

**Comment by hne3** [comment]
Not seeing where that commit fixes it. Could you point it out, please?

**Comment by 12wrigja** [comment]
For the record: this was fixed as a part of the modifications to the class FoodDatabaseTests.php and to the way that testing is set up with an environment file. There might be further changes so that this process is simplified in the future.
