### ISSUE TITLE
Report nutritional requirements for user

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#23]
Report nutritional requirements based on age/height/weight/gender/etc.

**Comment by 12wrigja** [comment]
See PR #31

**Comment by 12wrigja** [comment]
Also, it seems like the various values do not depend on the user's weight or height. Either we need to adjust the data so that that matters, or remove them from the list of attributes a user is asked for. 

@hne3 @lucyktan @las203

**Comment by lucyktan** [comment]
I think weight and height are used for recommended calories

**Comment by 12wrigja** [comment]
@las203 How do we compute recommended calories for a user? As far as I can tell that is not included i the seeder data you provided earlier.

**Comment by las203** [comment]
Honestly, I'd just ask the user to tell us how many calories they want to eat. It has a lot to do with how active the person is(plus weight, height, sex), and I don't think whatever I'd end up calculating for a recommended amount is going to be very accurate anyway. Just put default to be 2,000 and let them change it if they want.

**Comment by 12wrigja** [comment]
Got it. Thanks.

In that case, do we need the weight and height of a user, or should we remove that?

@hne3, @lucyktan , @oeihiko Chime in if you think that we still need those pieces of data.

**Comment by las203** [comment]
I didn't use it in any of my nutrient value recommendations. I don't think we need it at all.
