### ISSUE TITLE
Some foods return error when searching for nutritional property

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#24]
Example: 
$food = App\food::GetNameSimilarTo("apple")[0];
 $food->getCopper()
PHP error:  Trying to get property of non-object in /home/vagrant/Code/EECS393Project/EECS-393-Nutrition-App/app/food.php on line 97

**Comment by 12wrigja** [comment]
Should be fixed in Commit 0ef7d3c11c1f7583daee9ab93b25998794a3a408. See PR.
