### ISSUE TITLE
Stress + Load Testing w/Apache Benchmark

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#34]
Section 4c, testing doc: "In order to perform Load and Performance testing, we are going to use Apache Benchmark. This software is able to simulate simultaneous page requests to the browser and report back data on how successful the server was at handling those requests. Using this data we are able to set performance baselines, which we can test against as we continue to work on the application in order to make sure that no one piece of code is particularly inefficient."

**Comment by 12wrigja** [comment]
I would check with Podgurski and see if we need to do this - I'm pretty sure we only need to do unit and functional testing for our application.

**Comment by 12wrigja** [comment]
Was this closed because we don't need to do it? Can we get a close reason?

**Comment by hne3** [comment]
I'm planning to refile an issue for the 12/6 deadline that puts all of the miscellaneous testing tasks into one issue. I felt they were cluttering the issues dashboard, and don't think they all warrant individual tasks.

**Comment by 12wrigja** [comment]
Ok. Can we confirm with Podgurski that we need to do all these kinds of testing? because it seems a bit extreme to have to do stress/load/performance stuff....
