### ISSUE TITLE
Registration broken on master.

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#38]
Master gives error: 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'bdate' in 'field list' (SQL: insert into `users` (`name`, `email`, `password`, `bdate`, `gender`, `weight`, `height`, `updated_at`, `created_at`) values (test1, test1@test1.com, y$n2lElxOT.qkgSxC0cUBQKu/WCZdRIGZd1oGAcTS2lWlT/cSDbzc0e, 9/23/1995, 1, 150, 63, 2015-11-10 23:27:09, 2015-11-10 23:27:09))

upon registration.

**Comment by 12wrigja** [comment]
Is this broken on automated builds, or just on your computer? If its the latter, you probably need to remigrate your database.

php artisan migrate:refresh --seed
