### ISSUE TITLE
Change app name

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#42]
"Snackr" is already taken. Need to rename app and change display name on site.

**Comment by lucyktan** [comment]
Some words that I got from here (http://www.thesaurus.com/browse/eat): chomps, sate, nosh

**Comment by 12wrigja** [comment]
What about if we called it nutr.io? Sufficiently weird and new-age web
app-ish.

**Comment by lucyktan** [comment]
That's pretty clever, but saying nutr sounds like neuter :P

**Comment by 12wrigja** [comment]
Haha I didn't think of it like that - its supposed to be pronounced like
the first half of the word nutritious.

Scrap my idea lol.
