### ISSUE TITLE
/history returns error when user hasn't added any foods yet

### ISSUE THREAD

**Issue by lucyktan** [hne3/EECS-393-Nutrition-App#44]

**Comment by lucyktan** [comment]
This should be fixed when the user adds their five favorite foods at registration @oeihiko (also, automatically set quantity to 0 for these foods)

**Comment by 12wrigja** [comment]
This is actually caused by line 88 in history.blade.php where you are referencing a variable called allNutrients which does not exist. If you change that to nutrients then the page works.
