### ISSUE TITLE
Parametric search

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#48]
"Advanced search" should include ability to search by specific parameters, i.e. fat content, carb content, etc.

**Comment by lucyktan** [comment]
You can now sort search results by calories (default search is alphabetical). Sorting by nutrients is still being figured out (HELP).

**Comment by 12wrigja** [comment]
Help? What isn't working? What have you tried?

James

**Comment by lucyktan** [comment]
I can't do $food->sortBy(<nutrient_id>)... you can look at the commented-out part of FoodSearchController to see.

**Comment by 12wrigja** [comment]
I just updated the branch to have what i believe is the correct syntax.

**Comment by lucyktan** [comment]
Yes, it's right! Thanks :D
