### ISSUE TITLE
Getting a suggestion if you've never rated a food gives error

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#51]
ErrorException in User.php line 141: Undefined offset: 0

**Comment by lucyktan** [comment]
Which branch is this?

**Comment by hne3** [comment]
Enhancements

**Comment by lucyktan** [comment]
It should be working on RecSystem. Enhancements is behind on that.

**Comment by hne3** [comment]
Is RecSystem ready to merge? If so, could you file a pull request?

**Comment by lucyktan** [comment]
Nope, there are still some things to tweak. Look at comments in issue 47

**Comment by lucyktan** [comment]
I think this is still a bug that @12wrigja might continue working on.

**Comment by 12wrigja** [comment]
When is this due by? I won't have the time to fix it until after the upcoming friday...

**Comment by hne3** [comment]
Sorry I didn't notice this until now. This is due on Friday, December 4th. If you can't work on it, I'm happy to take it on.

**Comment by lucyktan** [comment]
No worries, it should be fixed now :)

**Comment by 12wrigja** [comment]
Fixed where?

**Comment by lucyktan** [comment]
In User.php in master. 
Also, I saw that the restrictions functionality was working during the demo, but for some reason, it's not anymore... I reseeded too.

**Comment by 12wrigja** [comment]
Ok. I'll go have a look at some point tonight.

The restrictions that were in place during the demo were done manually
using tinker and the addRestriction function in Food.php.
