### ISSUE TITLE
Ability to rate food/say "yes" or "no" to a suggestion

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#6]
User should be able to rate foods they've eaten on a 1-5 scale. They should also be able to accept or deny a food suggestion.

**Comment by hne3** [comment]
This is wrapped into Lucy's daily logging task, and relies on it for completion. Issue will be reopened at a later date.

**Comment by lucyktan** [comment]
I can work on this issue, since I already have the functionality on UserFoodHistory.

**Comment by hne3** [comment]
Awesome.

**Comment by lucyktan** [comment]
Where is the recommendation page for me to add the Eat Now button?
