### ISSUE TITLE
Filters for food sensitivities

### ISSUE THREAD

**Issue by hne3** [hne3/EECS-393-Nutrition-App#8]
Filter or flag foods containing dairy/gluten/nuts/chocolate based on user sensitivities. Flag suggested as you don't have to catch every food if it's written as a warning.

**Comment by 12wrigja** [comment]
Included as of commit  ca4b820. Food's 3 search methods (GetByName, SearchByName, and GetNameSimilarTo) now all accept an array of restrictions to filter out foods that aren't compatible with those restrictions. For the length of an entire request, you can also enable/disable honoring those restrictions by doing Food::ObeyRestrictions(true/false) respectively.
